var c=null,h;function s(a,d){function b(){}b.prototype=d.prototype;a.T=d.prototype;a.prototype=new b};function t(){var a=document.createElement("canvas");a.width=void 0;a.height=void 0;this.H=a};function u(a,d,b,f){this.d(a,d,b,f)}var v=c;h=u.prototype;h.color="transparent";h.offsetX=0;h.offsetY=0;h.blur=0;h.d=function(a,d,b,f){this.color=a;this.offsetX=d;this.offsetY=b;this.blur=f};h.toString=function(){return"[Shadow]"};v=new u("transparent",0,0,0);function w(a,d,b,f,j,g){this.d(a,d,b,f,j,g)}var z=Math.PI/180;h=w.prototype;h.f=1;h.b=0;h.g=0;h.c=1;h.e=0;h.a=0;h.alpha=1;h.i=c;h.h=c;h.d=function(a,d,b,f,j,g){if(a!=c)this.f=a;this.b=d||0;this.g=b||0;if(f!=c)this.c=f;this.e=j||0;this.a=g||0};function A(a,d,b,f,j,g,i){var l=a.e;if(d!=1||b!=0||f!=0||j!=1){var e=a.f,k=a.g;a.f=e*d+a.b*f;a.b=e*b+a.b*j;a.g=k*d+a.c*f;a.c=k*b+a.c*j}a.e=l*d+a.a*f+g;a.a=l*b+a.a*j+i}
h.append=function(a,d,b,f,j,g){var i=this.f,l=this.b,e=this.g,k=this.c;this.f=a*i+d*e;this.b=a*l+d*k;this.g=b*i+f*e;this.c=b*l+f*k;this.e=j*i+g*e+this.e;this.a=j*l+g*k+this.a};h.toString=function(){return"[Matrix2D (a="+this.f+" b="+this.b+" c="+this.g+" d="+this.c+" tx="+this.e+" ty="+this.a+")]"};new w(1,0,0,1,0,0);var B=0;function E(){this.d()}var F=document.createElement("canvas");F.width=F.height=1;var G=F.getContext("2d");h=E.prototype;h.alpha=1;h.u=c;h.id=-1;h.Q=!0;h.name=c;h.parent=c;h.C=0;h.D=0;h.rotation=0;h.r=1;h.s=1;h.F=0;h.G=0;h.i=c;h.N=!0;h.x=0;h.y=0;h.h=c;h.S=!1;h.z=c;h.w=c;h.n=c;h.K=c;h.J=c;h.O=0;h.P=0;h.t=c;h.d=function(){this.id=B++;this.t=new w};h.B=function(){return this.N&&this.alpha>0&&this.r!=0&&this.s!=0};h.q=function(a,d){if(d||!this.u)return!1;a.drawImage(this.u,this.O,this.P);return!0};
h.setTransform=function(a,d,b,f,j,g,i,l,e){this.x=a||0;this.y=d||0;this.r=b==c?1:b;this.s=f==c?1:f;this.rotation=j||0;this.F=g||0;this.G=i||0;this.C=l||0;this.D=e||0};
function H(a,d){if(d){var b=d;b.alpha=b.f=b.c=1;b.b=b.g=b.e=b.a=0;b.i=b.h=c}else d=new w;for(b=a;b!=c;){var f=d,j=b.x,g=b.y,i=b.r,l=b.s,e=b.rotation,k=b.F,n=b.G,o=b.C,q=b.D;if(e%360)var m=e*z,e=Math.cos(m),m=Math.sin(m);else e=1,m=0;if(o||q)f.e-=o,f.a-=q;k||n?(k*=z,n*=z,A(f,e*i,m*i,-m*l,e*l,0,0),A(f,Math.cos(n),Math.sin(n),-Math.sin(k),Math.cos(k),j,g)):A(f,e*i,m*i,-m*l,e*l,j,g);f=d;j=b.i;g=b.h;f.alpha*=b.alpha;f.i=f.i||j;f.h=f.h||g;b=b.parent}}
h.toString=function(){return"[DisplayObject (name="+this.name+")]"};function I(a,d){d=d||v;a.shadowColor=d.color;a.shadowOffsetX=d.offsetX;a.shadowOffsetY=d.offsetY;a.shadowBlur=d.blur}function J(){try{var a=G.getImageData(0,0,1,1).data[3]>1}catch(d){throw"An error has occured. This is most likely due to security restrictions on reading canvas pixel data with local or cross-domain images.";}return a};function K(){this.d()}s(K,E);h=K.prototype;h.children=c;h.d=function(){E.prototype.d.call();this.children=[]};h.B=function(){return!!this.N&&this.alpha>0&&!!this.children.length&&this.r!=0&&this.s!=0};
h.q=function(a,d,b){var f=L;if(E.prototype.q.call(this,a,d))return!0;if(!b){var b=this.t,d=this.alpha,j=this.i,g=this.h;b.d(1,0,0,1,0,0);b.alpha=d||1;b.i=j;b.h=g}d=this.children.length;j=this.children.slice(0);for(g=0;g<d;g++){var i=j[g];if(i.B()){var l=!1,e;e=i.t;var k=b.alpha,n=b.i,o=b.h;e.d(b.f,b.b,b.g,b.c,b.e,b.a);e.alpha=k||1;e.i=n;e.h=o;var k=e,n=i.x,o=i.y,q=i.r,m=i.s,p=i.rotation,x=i.F,y=i.G,C=i.C,D=i.D;if(p%360==0&&q==1&&m==1&&x==0&&y==0)k.e+=n-C,k.a+=o-D;else{if(p%360)var r=p*z,p=Math.cos(r),
r=Math.sin(r);else p=1,r=0;x||y?(x*=z,y*=z,k.append(Math.cos(y),Math.sin(y),-Math.sin(x),Math.cos(x),n,o),k.append(p*q,r*q,-r*m,p*m,0,0)):k.append(p*q,r*q,-r*m,p*m,n,o);if(C||D)k.e-=C*k.f+D*k.g,k.a-=C*k.b+D*k.c}k=e;n=i.i;o=i.h;k.alpha*=i.alpha;k.i=n||k.i;k.h=o||k.h;if(!(i instanceof K&&i.u==c))f&&i.S&&e.f==1&&e.b==0&&e.g==0&&e.c==1?a.setTransform(e.f,e.b,e.g,e.c,e.e+0.5|0,e.a+0.5|0):a.setTransform(e.f,e.b,e.g,e.c,e.e,e.a),a.globalAlpha=e.alpha,a.globalCompositeOperation=e.h||"source-over",(l=e.i)&&
I(a,l);i.q(a,!1,e);l&&I(a,l)}}return!0};h.toString=function(){return"[Container (name="+this.name+")]"};
function M(a,d,b,f,j){var g=a.t,i=j&1&&(a.z||a.w||a.n)||j&2&&(a.K||a.J);if(a.u)if(H(a,g),G.setTransform(g.f,g.b,g.g,g.c,g.e-d,g.a-b),G.globalAlpha=g.alpha,a.q(G),J()){if(F.width=0,F.width=1,i)return[a]}else return[];for(var l=a.children.length-1;l>=0;l--){var e=a.children[l];if(e.B()&&e.Q)if(e instanceof K)if(i){if(e=M(e,d,b))return[a]}else{if(e=M(e,d,b,f,j),!f&&e)return e}else if(!j||i||j&1&&(e.z||e.w||e.n)||j&2&&(e.K||e.J))if(H(e,g),G.setTransform(g.f,g.b,g.g,g.c,g.e-d,g.a-b),G.globalAlpha=g.alpha,
e.q(G),J())if(F.width=0,F.width=1,i)return[a];else if(f)f.push(e);else return[e]}return c};function N(a,d,b,f,j){this.d(a,d,b,f,j)}h=N.prototype;h.L=0;h.M=0;h.type=c;h.R=c;h.o=c;h.p=c;h.target=c;h.d=function(a,d,b,f,j){this.type=a;this.L=d;this.M=b;this.target=f;this.R=j};h.toString=function(){return"[MouseEvent (type="+this.type+" stageX="+this.L+" stageY="+this.M+")]"};function O(a){this.d(a)}s(O,K);var L=!1;h=O.prototype;h.canvas=c;h.j=0;h.k=0;h.o=c;h.p=c;h.I=c;h.v=!1;h.l=c;h.m=c;h.A=c;h.d=function(a){K.prototype.d.call(this);this.canvas=a;P(this)};h.toString=function(){return"[Stage (name="+this.name+")]"};
function P(a){var d=window.addEventListener?window:document;d.addEventListener("mouseup",function(b){var f=new N("onMouseUp",a.j,a.k,a,b);a.p&&a.p(f);a.l&&a.l.p&&a.l.p(f);a.m&&a.m.w&&M(a,a.j,a.k,c,a.A?3:1)[0]==a.m&&a.m.w(new N("onClick",a.j,a.k,a.m,b));a.l=a.m=c},!1);d.addEventListener("mousemove",function(b){if(a.canvas){if(!b)b=window.event;var f=a.v,d=b.pageX,g=b.pageY,i=a.canvas;do d-=i.offsetLeft,g-=i.offsetTop;while(i=i.offsetParent);a.v=d>=0&&g>=0&&d<a.canvas.width&&g<a.canvas.height;if(a.v)a.j=
d,a.k=g;if(f||a.v)b=new N("onMouseMove",a.j,a.k,a,b),a.o&&a.o(b),a.l&&a.l.o&&a.l.o(b)}else a.j=a.k=0},!1);d.addEventListener("dblclick",function(b){a.n&&a.n(new N("onDoubleClick",a.j,a.k,a,b));var d=M(a,a.j,a.k,c,a.A?3:1)[0]||c;d&&d.n instanceof Function&&d.n(new N("onPress",a.j,a.k,d,b))},!1);a.canvas.addEventListener("mousedown",function(b){a.I&&a.I(new N("onMouseDown",a.j,a.k,a,b));var d=M(a,a.j,a.k,c,a.A?3:1)[0]||c;if(d){if(d.z instanceof Function&&(b=new N("onPress",a.j,a.k,d,b),d.z(b),b.o||
b.p))a.l=b;a.m=d}},!1)};window.onload=function(){var a=new t;new O(a.H);document.body.appendChild(a.H)};
